export type SchemaCategory = 'entity' | 'manifest' | 'policy' | 'presentation' | 'validation' | 'validation_issue';

export interface SchemaCatalogEntry {
  readonly name: string;
  readonly category: SchemaCategory;
  readonly sourcePath: string;
  readonly yamlPath?: string;
  readonly docPath?: string;
  readonly summary: string;
  readonly purpose: string;
  readonly references: readonly string[];
}

export const CELL_SCHEMA_CATALOG: readonly SchemaCatalogEntry[] = [
  {
    name: 'CellManifestV1Schema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/CellManifestV1Schema.ts',
    yamlPath: 'manifests/cell-manifest.schema.yaml',
    docPath: 'manifests/cell-manifest.schema.md',
    summary: 'Canonical top-level Cell manifest contract.',
    purpose: 'Validates metadata and spec sections that compose entities, pages, navigation, and shell.',
    references: ['EntityDefinitionSchema', 'RoleDefinitionSchema'],
  },
  {
    name: 'CellMetadataSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/CellMetadataSchema.ts',
    yamlPath: 'manifests/metadata.schema.yaml',
    docPath: 'manifests/metadata.schema.md',
    summary: 'Manifest identity contract.',
    purpose: 'Validates manifest key, name, version, and optional description.',
    references: [],
  },
  {
    name: 'CellSpecSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/CellSpecSchema.ts',
    yamlPath: 'manifests/cell-spec.schema.yaml',
    docPath: 'manifests/cell-spec.schema.md',
    summary: 'Specification body contract for a Cell manifest.',
    purpose: 'Validates the spec block that composes mount, entities, pages, navigation, roles, and app shell.',
    references: ['CellMountDefinitionSchema', 'EntityDefinitionSchema', 'PageDefinitionSchema', 'NavigationDefinitionSchema', 'RoleDefinitionSchema', 'AppShellDefinitionSchema'],
  },
  {
    name: 'AppShellDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/shell/AppShellDefinitionSchema.ts',
    yamlPath: 'manifests/app-shell/app-shell.schema.yaml',
    docPath: 'manifests/app-shell/app-shell.schema.md',
    summary: 'App shell composition contract.',
    purpose: 'Validates shell layout, regions, shell navigation, capabilities, and responsive behavior.',
    references: [],
  },
  {
    name: 'CellMountDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/shell/CellMountDefinitionSchema.ts',
    yamlPath: 'manifests/shared/mount.schema.yaml',
    docPath: 'manifests/shared/mount.schema.md',
    summary: 'Cell mount-point contract.',
    purpose: 'Validates route mount path and landing page selection for the cell entry point.',
    references: ['PageDefinitionSchema'],
  },
  {
    name: 'EntityDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/EntityDefinitionSchema.ts',
    yamlPath: 'manifests/entities/entity-definition.schema.yaml',
    docPath: 'manifests/entities/entity-definition.schema.md',
    summary: 'Canonical entity contract for one business entity.',
    purpose:
      'Validates the full entity shape including fields, relations, computed fields, lifecycle, events, capabilities, policies, and entity-level validation.',
    references: [
      'FieldDefinitionSchema',
      'RelationDefinitionSchema',
      'ComputedFieldDefinitionSchema',
      'LifecycleDefinitionSchema',
      'EventDefinitionSchema',
      'CapabilityDefinitionSchema',
      'EntityPoliciesDefinitionSchema',
      'FieldPoliciesDefinitionSchema',
      'EntityValidationSchema',
    ],
  },
  {
    name: 'EntityValidationSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/EntityValidationSchema.ts',
    yamlPath: 'manifests/entities/entity-validation.schema.yaml',
    docPath: 'manifests/entities/entity-validation.schema.md',
    summary: 'Entity-level and server-level validation declaration block.',
    purpose: 'Validates cross-field invariants and async/server validator references attached to an entity.',
    references: ['EntityRuleDefinitionSchema', 'CrossEntityValidatorRefSchema'],
  },
  {
    name: 'FieldDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/field/FieldDefinitionSchema.ts',
    yamlPath: 'manifests/entities/field-definition.schema.yaml',
    docPath: 'manifests/entities/field-definition.schema.md',
    summary: 'Declarative field contract used by entities and nested objects.',
    purpose: 'Validates field identity, type, UX metadata, nested object fields, and validation block references.',
    references: ['DisplayDefinitionSchema', 'FieldValidationSchema'],
  },
  {
    name: 'DisplayTypeSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    yamlPath: 'manifests/entities/display.schema.yaml',
    docPath: 'manifests/entities/display.schema.md',
    summary: 'Field display renderer type taxonomy.',
    purpose: 'Validates allowed renderer types used by field display configuration.',
    references: [],
  },
  {
    name: 'DisplayAlignSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    yamlPath: 'manifests/entities/display.schema.yaml',
    docPath: 'manifests/entities/display.schema.md',
    summary: 'Field display alignment taxonomy.',
    purpose: 'Validates allowed horizontal alignment values for field display configuration.',
    references: [],
  },
  {
    name: 'DisplayDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    yamlPath: 'manifests/entities/display.schema.yaml',
    docPath: 'manifests/entities/display.schema.md',
    summary: 'Field display configuration contract.',
    purpose:
      'Validates renderer-specific display options, formatting, mappings, and guardrails for field presentation.',
    references: ['DisplayTypeSchema', 'DisplayAlignSchema'],
  },
  {
    name: 'RelationDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/relation/RelationDefinitionSchema.ts',
    yamlPath: 'manifests/entities/relation-definition.schema.yaml',
    docPath: 'manifests/entities/relation-definition.schema.md',
    summary: 'Relationship contract between entities.',
    purpose: 'Validates belongs-to, has-many, many-to-many, self, and polymorphic relationship declarations.',
    references: [],
  },
  {
    name: 'ComputedFieldDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/field/ComputedFieldDefinitionSchema.ts',
    yamlPath: 'manifests/entities/computed-field.schema.yaml',
    docPath: 'manifests/entities/computed-field.schema.md',
    summary: 'Derived field contract.',
    purpose: 'Validates expression, conditional, and aggregation computed field definitions.',
    references: ['RelationDefinitionSchema'],
  },
  {
    name: 'LifecycleTransitionDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/lifecycle/LifecycleTransitionDefinitionSchema.ts',
    yamlPath: 'manifests/entities/lifecycle-transition.schema.yaml',
    docPath: 'manifests/entities/lifecycle-transition.schema.md',
    summary: 'State transition rule for lifecycle engines.',
    purpose: 'Validates from/to transition structure, optional guards, hooks, and event naming.',
    references: [],
  },
  {
    name: 'LifecycleDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
    yamlPath: 'manifests/entities/lifecycle.schema.yaml',
    docPath: 'manifests/entities/lifecycle.schema.md',
    summary: 'Entity state machine contract.',
    purpose: 'Validates lifecycle field selection, allowed states, initial state, and transition definitions.',
    references: ['LifecycleTransitionDefinitionSchema'],
  },
  {
    name: 'DomainEventActorTypeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventActorTypeSchema.ts',
    docPath: 'libs/cell-contract/src/contract/manifest/domain-event/DomainEventActorTypeSchema.md',
    summary: 'Actor type taxonomy for event envelopes.',
    purpose: 'Validates allowed actor type enum values used by event metadata.',
    references: [],
  },
  {
    name: 'DomainEventActorSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
    docPath: 'libs/cell-contract/src/contract/manifest/domain-event/DomainEventActorSchema.md',
    summary: 'Event actor identity contract.',
    purpose: 'Validates who triggered the domain event and optional actor metadata.',
    references: ['DomainEventActorTypeSchema'],
  },
  {
    name: 'DomainEventEntityRefSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventEntityRefSchema.ts',
    docPath: 'libs/cell-contract/src/contract/manifest/domain-event/DomainEventEntityRefSchema.md',
    summary: 'Event entity reference contract.',
    purpose: 'Validates normalized references to entity type and identifier inside event payloads.',
    references: [],
  },
  {
    name: 'DomainEventEnvelopeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
    docPath: 'libs/cell-contract/src/contract/manifest/domain-event/DomainEventEnvelopeSchema.md',
    summary: 'Domain event transport envelope contract.',
    purpose: 'Validates event metadata and payload pointers used in audit and timeline surfaces.',
    references: ['DomainEventActorSchema', 'DomainEventEntityRefSchema'],
  },
  {
    name: 'EventDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/event/EventDefinitionSchema.ts',
    yamlPath: 'manifests/entities/event.schema.yaml',
    docPath: 'manifests/entities/event.schema.md',
    summary: 'Entity-level event customization contract.',
    purpose: 'Validates excluded fields and naming overrides for create/update/delete lifecycle event streams.',
    references: ['DomainEventEnvelopeSchema'],
  },
  {
    name: 'CapabilityInputTypeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityInputTypeSchema.ts',
    yamlPath: 'manifests/entities/capability-input.schema.yaml',
    docPath: 'manifests/entities/capability-input.schema.md',
    summary: 'Capability input field type taxonomy.',
    purpose: 'Validates supported input types used in capability action forms.',
    references: [],
  },
  {
    name: 'CapabilityInputDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
    yamlPath: 'manifests/entities/capability-input.schema.yaml',
    docPath: 'manifests/entities/capability-input.schema.md',
    summary: 'Capability input declaration contract.',
    purpose: 'Validates action input key, type, labels, required flags, and optional enum values.',
    references: ['CapabilityInputTypeSchema'],
  },
  {
    name: 'CapabilityDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
    yamlPath: 'manifests/entities/capability-definition.schema.yaml',
    docPath: 'manifests/entities/capability-definition.schema.md',
    summary: 'Entity action capability contract.',
    purpose: 'Validates transition, mutation, workflow, export, and integration capability declarations.',
    references: ['CapabilityInputDefinitionSchema'],
  },
  {
    name: 'PolicyScopeSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/PolicyScopeSchema.ts',
    yamlPath: 'manifests/entities/policy.schema.yaml',
    docPath: 'manifests/entities/policy.schema.md',
    summary: 'Policy scope taxonomy.',
    purpose: 'Validates allowed policy scopes used by action-level access rules.',
    references: [],
  },
  {
    name: 'ActionPolicySchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/ActionPolicySchema.ts',
    yamlPath: 'manifests/entities/policy.schema.yaml',
    docPath: 'manifests/entities/policy.schema.md',
    summary: 'One action-to-scope policy rule.',
    purpose: 'Validates required scope and optional condition for an entity or field action.',
    references: ['PolicyScopeSchema'],
  },
  {
    name: 'EntityPoliciesDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
    yamlPath: 'manifests/entities/policy.schema.yaml',
    docPath: 'manifests/entities/policy.schema.md',
    summary: 'Entity-level authorization policy set.',
    purpose: 'Validates create/read/update/delete and custom action policy declarations for one entity.',
    references: ['ActionPolicySchema'],
  },
  {
    name: 'FieldPoliciesDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
    yamlPath: 'manifests/entities/policy.schema.yaml',
    docPath: 'manifests/entities/policy.schema.md',
    summary: 'Per-field authorization policy map.',
    purpose: 'Validates field-level view and update scope requirements as overrides.',
    references: ['ActionPolicySchema'],
  },
  {
    name: 'RoleDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/manifest/role/RoleDefinitionSchema.ts',
    yamlPath: 'manifests/roles/role-definition.schema.yaml',
    docPath: 'manifests/roles/role-definition.schema.md',
    summary: 'Role bundle definition for policy scopes.',
    purpose: 'Validates role keys, labels, and associated scope grants for permission composition.',
    references: [],
  },
  {
    name: 'NavigationDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/navigation/NavigationDefinitionSchema.ts',
    yamlPath: 'manifests/navigation/navigation.schema.yaml',
    docPath: 'manifests/navigation/navigation.schema.md',
    summary: 'Navigation menu structure contract.',
    purpose: 'Validates the navigation tree composed of page references and nested groups.',
    references: ['PageDefinitionSchema'],
  },
  {
    name: 'PageDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/page/PageDefinitionSchema.ts',
    yamlPath: 'manifests/pages/page-definition.schema.yaml',
    docPath: 'manifests/pages/page-definition.schema.md',
    summary: 'Page definition contract.',
    purpose: 'Validates page key, type, title, path, entity binding, menu visibility, and data context.',
    references: ['EntityDefinitionSchema'],
  },
  {
    name: 'FieldValidationSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/field/FieldValidationSchema.ts',
    yamlPath: 'manifests/entities/field-validation.schema.yaml',
    docPath: 'manifests/entities/field-validation.schema.md',
    summary: 'Field-level validation container.',
    purpose: 'Validates the validation block attached to a field, containing an array of field rules.',
    references: ['FieldRuleDefinitionSchema'],
  },
  {
    name: 'ValidationScopeSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationScopeSchema.ts',
    docPath: 'libs/cell-contract/src/semantic/ValidationScopeSchema.md',
    summary: 'Issue scope taxonomy.',
    purpose:
      'Validates where a validation issue applies (field/entity/cross-entity/lifecycle/persistence/authorization).',
    references: [],
  },
  {
    name: 'ValidationSeveritySchema',
    category: 'validation_issue',
    sourcePath: 'src/shared/ValidationSeveritySchema.ts',
    docPath: 'libs/cell-contract/src/shared/ValidationSeveritySchema.md',
    summary: 'Validation severity taxonomy.',
    purpose: 'Validates issue severity values used by validators and UI result surfaces.',
    references: [],
  },
  {
    name: 'ValidationIssueSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationIssueSchema.ts',
    docPath: 'libs/cell-contract/src/semantic/ValidationIssueSchema.md',
    summary: 'Single validation issue contract.',
    purpose: 'Validates normalized issue structure including scope, path, severity, and user-facing messages.',
    references: ['ValidationScopeSchema', 'ValidationSeveritySchema'],
  },
  {
    name: 'ValidationErrorResponseSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationErrorResponseSchema.ts',
    docPath: 'libs/cell-contract/src/semantic/ValidationErrorResponseSchema.md',
    summary: 'Validation error API envelope.',
    purpose: 'Validates API response shape for aggregated validation failures.',
    references: ['ValidationIssueSchema'],
  },

  {
    name: 'FieldRuleTypeSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/field/FieldRuleTypeSchema.ts',
    yamlPath: 'manifests/entities/field-rule.schema.yaml',
    docPath: 'manifests/entities/field-rule.schema.md',
    summary: 'Field rule type taxonomy.',
    purpose: 'Validates built-in rule type values used in field validation declarations.',
    references: [],
  },
  {
    name: 'FieldRuleDefinitionSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
    yamlPath: 'manifests/entities/field-rule.schema.yaml',
    docPath: 'manifests/entities/field-rule.schema.md',
    summary: 'Field-level validation rule declaration.',
    purpose: 'Validates declarative constraints attached to a single field.',
    references: ['FieldRuleTypeSchema', 'ValidationSeveritySchema'],
  },
  {
    name: 'EntityRuleDefinitionSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
    docPath: 'libs/cell-contract/src/contract/entity/EntityRuleDefinitionSchema.md',
    summary: 'Entity-level invariant declaration.',
    purpose: 'Validates cross-field invariant rule contracts within one entity.',
    references: ['ValidationSeveritySchema'],
  },
  {
    name: 'CrossEntityValidatorRefSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
    docPath: 'libs/cell-contract/src/contract/entity/CrossEntityValidatorRefSchema.md',
    summary: 'Server-side validator reference contract.',
    purpose: 'Validates references to async validators used for cross-entity, lifecycle, and persistence checks.',
    references: ['ValidationSeveritySchema'],
  },
] as const;
