export type SchemaCategory = 'entity' | 'manifest' | 'policy' | 'presentation' | 'validation' | 'validation_issue';

export interface SchemaCatalogEntry {
  readonly name: string;
  readonly category: SchemaCategory;
  readonly sourcePath: string;
  readonly summary: string;
  readonly purpose: string;
  readonly references: readonly string[];
}

export const CELL_SCHEMA_CATALOG: readonly SchemaCatalogEntry[] = [
  {
    name: 'CellManifestV1Schema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/CellManifestV1Schema.ts',
    summary: 'Canonical top-level Cell manifest contract.',
    purpose: 'Validates metadata and spec sections that compose entities, pages, navigation, and shell.',
    references: ['EntityDefinitionSchema', 'RoleDefinitionSchema'],
  },
  {
    name: 'AppShellDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/shell/AppShellDefinitionSchema.ts',
    summary: 'App shell composition contract.',
    purpose: 'Validates shell layout, regions, shell navigation, capabilities, and responsive behavior.',
    references: [],
  },
  {
    name: 'CellMountDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/shell/CellMountDefinitionSchema.ts',
    summary: 'Cell mount-point contract.',
    purpose: 'Validates route mount path and landing page selection for the cell entry point.',
    references: ['PageDefinitionSchema'],
  },
  {
    name: 'EntityDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/EntityDefinitionSchema.ts',
    summary: 'Canonical entity contract for one business entity.',
    purpose:
      'Validates the full entity shape including fields, relations, computed fields, lifecycle, events, capabilities, policies, and entity-level validation.',
    references: [
      'FieldDefinitionSchema',
      'RelationDefinitionSchema',
      'ComputedFieldDefinitionSchema',
      'LifecycleDefinitionSchema',
      'EventDefinitionSchema',
      'CapabilityDefinitionSchema',
      'EntityPoliciesDefinitionSchema',
      'FieldPoliciesDefinitionSchema',
      'EntityValidationSchema',
    ],
  },
  {
    name: 'EntityValidationSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/EntityValidationSchema.ts',
    summary: 'Entity-level and server-level validation declaration block.',
    purpose: 'Validates cross-field invariants and async/server validator references attached to an entity.',
    references: ['EntityRuleDefinitionSchema', 'CrossEntityValidatorRefSchema'],
  },
  {
    name: 'FieldDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/field/FieldDefinitionSchema.ts',
    summary: 'Declarative field contract used by entities and nested objects.',
    purpose: 'Validates field identity, type, UX metadata, nested object fields, and validation block references.',
    references: ['DisplayDefinitionSchema', 'FieldValidationSchema'],
  },
  {
    name: 'DisplayTypeSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    summary: 'Field display renderer type taxonomy.',
    purpose: 'Validates allowed renderer types used by field display configuration.',
    references: [],
  },
  {
    name: 'DisplayAlignSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    summary: 'Field display alignment taxonomy.',
    purpose: 'Validates allowed horizontal alignment values for field display configuration.',
    references: [],
  },
  {
    name: 'DisplayDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
    summary: 'Field display configuration contract.',
    purpose:
      'Validates renderer-specific display options, formatting, mappings, and guardrails for field presentation.',
    references: ['DisplayTypeSchema', 'DisplayAlignSchema'],
  },
  {
    name: 'RelationDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/relation/RelationDefinitionSchema.ts',
    summary: 'Relationship contract between entities.',
    purpose: 'Validates belongs-to, has-many, many-to-many, self, and polymorphic relationship declarations.',
    references: [],
  },
  {
    name: 'ComputedFieldDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/field/ComputedFieldDefinitionSchema.ts',
    summary: 'Derived field contract.',
    purpose: 'Validates expression, conditional, and aggregation computed field definitions.',
    references: ['RelationDefinitionSchema'],
  },
  {
    name: 'LifecycleTransitionDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/lifecycle/LifecycleTransitionDefinitionSchema.ts',
    summary: 'State transition rule for lifecycle engines.',
    purpose: 'Validates from/to transition structure, optional guards, hooks, and event naming.',
    references: [],
  },
  {
    name: 'LifecycleDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
    summary: 'Entity state machine contract.',
    purpose: 'Validates lifecycle field selection, allowed states, initial state, and transition definitions.',
    references: ['LifecycleTransitionDefinitionSchema'],
  },
  {
    name: 'DomainEventActorTypeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventActorTypeSchema.ts',
    summary: 'Actor type taxonomy for event envelopes.',
    purpose: 'Validates allowed actor type enum values used by event metadata.',
    references: [],
  },
  {
    name: 'DomainEventActorSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
    summary: 'Event actor identity contract.',
    purpose: 'Validates who triggered the domain event and optional actor metadata.',
    references: ['DomainEventActorTypeSchema'],
  },
  {
    name: 'DomainEventEntityRefSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventEntityRefSchema.ts',
    summary: 'Event entity reference contract.',
    purpose: 'Validates normalized references to entity type and identifier inside event payloads.',
    references: [],
  },
  {
    name: 'DomainEventEnvelopeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
    summary: 'Domain event transport envelope contract.',
    purpose: 'Validates event metadata and payload pointers used in audit and timeline surfaces.',
    references: ['DomainEventActorSchema', 'DomainEventEntityRefSchema'],
  },
  {
    name: 'EventDefinitionSchema',
    category: 'entity',
    sourcePath: 'src/contract/entity/event/EventDefinitionSchema.ts',
    summary: 'Entity-level event customization contract.',
    purpose: 'Validates excluded fields and naming overrides for create/update/delete lifecycle event streams.',
    references: ['DomainEventEnvelopeSchema'],
  },
  {
    name: 'CapabilityInputTypeSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityInputTypeSchema.ts',
    summary: 'Capability input field type taxonomy.',
    purpose: 'Validates supported input types used in capability action forms.',
    references: [],
  },
  {
    name: 'CapabilityInputDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
    summary: 'Capability input declaration contract.',
    purpose: 'Validates action input key, type, labels, required flags, and optional enum values.',
    references: ['CapabilityInputTypeSchema'],
  },
  {
    name: 'CapabilityDefinitionSchema',
    category: 'manifest',
    sourcePath: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
    summary: 'Entity action capability contract.',
    purpose: 'Validates transition, mutation, workflow, export, and integration capability declarations.',
    references: ['CapabilityInputDefinitionSchema'],
  },
  {
    name: 'PolicyScopeSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/PolicyScopeSchema.ts',
    summary: 'Policy scope taxonomy.',
    purpose: 'Validates allowed policy scopes used by action-level access rules.',
    references: [],
  },
  {
    name: 'ActionPolicySchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/ActionPolicySchema.ts',
    summary: 'One action-to-scope policy rule.',
    purpose: 'Validates required scope and optional condition for an entity or field action.',
    references: ['PolicyScopeSchema'],
  },
  {
    name: 'EntityPoliciesDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
    summary: 'Entity-level authorization policy set.',
    purpose: 'Validates create/read/update/delete and custom action policy declarations for one entity.',
    references: ['ActionPolicySchema'],
  },
  {
    name: 'FieldPoliciesDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
    summary: 'Per-field authorization policy map.',
    purpose: 'Validates field-level view and update scope requirements as overrides.',
    references: ['ActionPolicySchema'],
  },
  {
    name: 'RoleDefinitionSchema',
    category: 'policy',
    sourcePath: 'src/contract/manifest/role/RoleDefinitionSchema.ts',
    summary: 'Role bundle definition for policy scopes.',
    purpose: 'Validates role keys, labels, and associated scope grants for permission composition.',
    references: [],
  },
  {
    name: 'ValidationScopeSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationScopeSchema.ts',
    summary: 'Issue scope taxonomy.',
    purpose:
      'Validates where a validation issue applies (field/entity/cross-entity/lifecycle/persistence/authorization).',
    references: [],
  },
  {
    name: 'ValidationSeveritySchema',
    category: 'validation_issue',
    sourcePath: 'src/shared/ValidationSeveritySchema.ts',
    summary: 'Validation severity taxonomy.',
    purpose: 'Validates issue severity values used by validators and UI result surfaces.',
    references: [],
  },
  {
    name: 'ValidationIssueSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationIssueSchema.ts',
    summary: 'Single validation issue contract.',
    purpose: 'Validates normalized issue structure including scope, path, severity, and user-facing messages.',
    references: ['ValidationScopeSchema', 'ValidationSeveritySchema'],
  },
  {
    name: 'ValidationErrorResponseSchema',
    category: 'validation_issue',
    sourcePath: 'src/semantic/ValidationErrorResponseSchema.ts',
    summary: 'Validation error API envelope.',
    purpose: 'Validates API response shape for aggregated validation failures.',
    references: ['ValidationIssueSchema'],
  },

  {
    name: 'FieldRuleTypeSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/field/FieldRuleTypeSchema.ts',
    summary: 'Field rule type taxonomy.',
    purpose: 'Validates built-in rule type values used in field validation declarations.',
    references: [],
  },
  {
    name: 'FieldRuleDefinitionSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
    summary: 'Field-level validation rule declaration.',
    purpose: 'Validates declarative constraints attached to a single field.',
    references: ['FieldRuleTypeSchema', 'ValidationSeveritySchema'],
  },
  {
    name: 'EntityRuleDefinitionSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
    summary: 'Entity-level invariant declaration.',
    purpose: 'Validates cross-field invariant rule contracts within one entity.',
    references: ['ValidationSeveritySchema'],
  },
  {
    name: 'CrossEntityValidatorRefSchema',
    category: 'validation',
    sourcePath: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
    summary: 'Server-side validator reference contract.',
    purpose: 'Validates references to async validators used for cross-entity, lifecycle, and persistence checks.',
    references: ['ValidationSeveritySchema'],
  },
] as const;
