import type { CellManifestV1 } from '@ikary/cell-contract-core';

export const SUPPORT_CELL_MANIFEST: CellManifestV1 = {
  apiVersion: 'ikary.co/v1alpha1',
  kind: 'Cell',
  metadata: {
    key: 'support',
    name: 'Support Center',
    description: 'Customer support ticket management',
    version: '1.0.0',
  },
  spec: {
    mount: {
      title: 'Support Center',
      mountPath: '/support',
      landingPage: 'ticket-list',
    },
    entities: [
      {
        key: 'ticket',
        name: 'Ticket',
        pluralName: 'Tickets',
        fields: [
          {
            key: 'subject',
            type: 'string',
            name: 'Subject',
            helpText: 'Brief description visible to the assigned agent.',
            smallTip: 'Keep it under 100 characters.',
            list: { visible: true, searchable: true },
            create: { visible: true, order: 0, placeholder: 'Describe the issue…' },
            validation: {
              fieldRules: [
                {
                  ruleId: 'ticket/subject-required@1',
                  type: 'required',
                  field: 'subject',
                  messageKey: 'ticket.subject.required',
                  defaultMessage: 'Subject is required.',
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
                {
                  ruleId: 'ticket/subject-min-length@1',
                  type: 'min_length',
                  field: 'subject',
                  messageKey: 'ticket.subject.minLength',
                  defaultMessage: 'Subject must be at least 3 characters.',
                  params: { min: 3 },
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
                {
                  ruleId: 'ticket/subject-max-length@1',
                  type: 'max_length',
                  field: 'subject',
                  messageKey: 'ticket.subject.maxLength',
                  defaultMessage: 'Subject must be at most 200 characters.',
                  params: { max: 200 },
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
              ],
            },
          },
          {
            key: 'status',
            type: 'enum',
            name: 'Status',
            enumValues: ['open', 'in_progress', 'resolved', 'closed'],
            list: { visible: true, filterable: true, sortable: true },
            create: { visible: true, order: 1 },
            validation: {
              fieldRules: [
                {
                  ruleId: 'ticket/status-required@1',
                  type: 'required',
                  field: 'status',
                  messageKey: 'ticket.status.required',
                  defaultMessage: 'Status is required.',
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
              ],
            },
          },
          {
            key: 'priority',
            type: 'enum',
            name: 'Priority',
            enumValues: ['low', 'medium', 'high', 'critical'],
            helpText: 'Affects SLA response time and queue position.',
            list: { visible: true, filterable: true, sortable: true },
            create: { visible: true, order: 2 },
          },
          {
            key: 'description',
            type: 'text',
            name: 'Description',
            list: { visible: false },
            create: { visible: true, order: 3, placeholder: 'Add more detail…' },
          },
          {
            key: 'customerId',
            type: 'string',
            name: 'Customer ID',
            smallTip: 'Leave blank to auto-assign based on queue rules.',
            list: { visible: false },
            create: { visible: true, order: 4 },
          },
        ],
      },
      {
        key: 'customer',
        name: 'Customer',
        pluralName: 'Customers',
        fields: [
          {
            key: 'name',
            type: 'string',
            name: 'Name',
            list: { visible: true },
            create: { visible: true, order: 0 },
            validation: {
              fieldRules: [
                {
                  ruleId: 'customer/name-required@1',
                  type: 'required',
                  field: 'name',
                  messageKey: 'customer.name.required',
                  defaultMessage: 'Name is required.',
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
              ],
            },
          },
          {
            key: 'email',
            type: 'string',
            name: 'Email',
            list: { visible: true },
            create: { visible: true, order: 1, placeholder: 'email@example.com' },
            validation: {
              fieldRules: [
                {
                  ruleId: 'customer/email-required@1',
                  type: 'required',
                  field: 'email',
                  messageKey: 'customer.email.required',
                  defaultMessage: 'Email is required.',
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
                {
                  ruleId: 'customer/email-format@1',
                  type: 'email',
                  field: 'email',
                  messageKey: 'customer.email.format',
                  defaultMessage: 'Email must be a valid email address.',
                  clientSafe: true,
                  blocking: true,
                  severity: 'error',
                },
              ],
            },
          },
          {
            key: 'plan',
            type: 'enum',
            name: 'Plan',
            enumValues: ['free', 'pro', 'enterprise'],
            list: { visible: true },
            create: { visible: true, order: 2 },
          },
        ],
      },
    ],
    pages: [
      {
        key: 'ticket-list',
        type: 'entity-list',
        title: 'Tickets',
        path: '/tickets',
        entity: 'ticket',
      },
      {
        key: 'ticket-detail',
        type: 'entity-detail',
        title: 'Ticket Detail',
        path: '/tickets/:id',
        entity: 'ticket',
      },
      {
        key: 'customer-list',
        type: 'entity-list',
        title: 'Customers',
        path: '/customers',
        entity: 'customer',
      },
      {
        key: 'customer-detail',
        type: 'entity-detail',
        title: 'Customer Detail',
        path: '/customers/:id',
        entity: 'customer',
      },
    ],
    navigation: {
      items: [
        {
          type: 'group',
          key: 'operations',
          label: 'Operations',
          order: 0,
          children: [
            { type: 'page', key: 'nav-tickets', pageKey: 'ticket-list', label: 'Tickets', order: 0 },
            { type: 'page', key: 'nav-customers', pageKey: 'customer-list', label: 'Customers', order: 1 },
          ],
        },
      ],
    },
  },
};
