import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Bug, Download, RefreshCw, RotateCcw } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/button';
import {
  buildStudioBundle,
  buildStudioDebugBundle,
  downloadStudioBundle,
  downloadStudioDebugBundle,
} from '../features/studio/export-bundle';
import { OpenAiResponsesClient } from '../features/studio/openai-responses.client';
import { StudioArtifactService } from '../features/studio/studio-artifact.service';
import { StudioMessageService } from '../features/studio/studio-message.service';
import { StudioOrchestratorService } from '../features/studio/studio-orchestrator.service';
import { StudioPreviewService } from '../features/studio/studio-preview.service';
import { StudioSessionService } from '../features/studio/studio-session.service';
import { StudioStore } from '../features/studio/studio-store';
import { StudioChatPane } from '../features/studio/components/studio-chat-pane';
import { StudioPreviewPane } from '../features/studio/components/studio-preview-pane';
import type {
  StudioDebugTraceEvent,
  StudioLlmExchangeRecord,
  StudioOrchestrationResult,
} from '../features/studio/contracts';
import {
  refreshStudioState as refreshStudioStateQuery,
  useStudioGenerateInitial,
  useStudioModelCatalog,
  useStudioSendTurn,
  useStudioState,
} from './hooks/useStudioPageData';

interface StudioServices {
  store: StudioStore;
  sessionService: StudioSessionService;
  messageService: StudioMessageService;
  artifactService: StudioArtifactService;
  previewService: StudioPreviewService;
  openAiClient: OpenAiResponsesClient;
  orchestrator: StudioOrchestratorService;
}

interface StudioPageState {
  sessionId: string;
  phase: StudioOrchestrationResult['phase'];
  messages: ReturnType<StudioMessageService['list']>;
  artifacts: ReturnType<StudioArtifactService['list']>;
  currentArtifacts: ReturnType<StudioArtifactService['getCurrentArtifactSet']>;
  preview: ReturnType<StudioOrchestratorService['buildPreviewModel']>;
}

const DEFAULT_STUDIO_MODELS = ['gpt-4o-mini', 'gpt-4.1-mini', 'gpt-4.1', 'o4-mini'] as const;
const MAX_TRACE_EVENTS = 400;
const MAX_LLM_EXCHANGES = 120;

function createStudioServices(): StudioServices {
  const store = new StudioStore();
  const sessionService = new StudioSessionService(store);
  const messageService = new StudioMessageService(store);
  const artifactService = new StudioArtifactService(store);
  const previewService = new StudioPreviewService();
  const openAiClient = new OpenAiResponsesClient();
  const orchestrator = new StudioOrchestratorService(
    sessionService,
    messageService,
    artifactService,
    previewService,
    openAiClient,
  );

  return {
    store,
    sessionService,
    messageService,
    artifactService,
    previewService,
    openAiClient,
    orchestrator,
  };
}

interface StudioPageProps {
  backPath?: string;
}

export function StudioPage({ backPath = '/' }: StudioPageProps) {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const services = useMemo(() => createStudioServices(), []);
  const [selectedModel, setSelectedModel] = useState(() => services.openAiClient.getModel());
  const [debugMode, setDebugMode] = useState(true);
  const [statusWord, setStatusWord] = useState<string | null>(null);
  const [latestError, setLatestError] = useState<string | null>(null);
  const [lastRunResult, setLastRunResult] = useState<StudioOrchestrationResult | null>(null);
  const [debugTraces, setDebugTraces] = useState<StudioDebugTraceEvent[]>([]);
  const [llmExchanges, setLlmExchanges] = useState<StudioLlmExchangeRecord[]>([]);
  const autoGeneratedPlanVersionRef = useRef<number | null>(null);
  const appendTrace = useCallback((event: StudioDebugTraceEvent) => {
    setDebugTraces((previous) => {
      const next = [...previous, event];
      return next.length > MAX_TRACE_EVENTS ? next.slice(next.length - MAX_TRACE_EVENTS) : next;
    });
  }, []);
  const traceUi = useCallback(
    (stage: string, message: string, level: StudioDebugTraceEvent['level'] = 'info', details?: unknown) => {
      appendTrace({
        at: new Date().toISOString(),
        source: 'ui',
        component: 'StudioPage',
        stage,
        level,
        message,
        details,
      });
    },
    [appendTrace],
  );
  const appendLlmExchange = useCallback((exchange: StudioLlmExchangeRecord) => {
    setLlmExchanges((previous) => {
      const next = [...previous, exchange];
      return next.length > MAX_LLM_EXCHANGES ? next.slice(next.length - MAX_LLM_EXCHANGES) : next;
    });
  }, []);
  const modelOptions = useMemo(() => {
    const envOptionsRaw =
      typeof import.meta !== 'undefined'
        ? (import.meta.env.VITE_STUDIO_MODEL_OPTIONS as string | undefined)
        : undefined;
    const envOptions = (envOptionsRaw ?? '')
      .split(',')
      .map((value) => value.trim())
      .filter((value) => value.length > 0);

    const combined = [...DEFAULT_STUDIO_MODELS, ...envOptions, selectedModel];
    return [...new Set(combined)];
  }, [selectedModel]);
  const modelCatalogQuery = useStudioModelCatalog(services.openAiClient);
  const allModelOptions = useMemo(() => {
    const fetched = modelCatalogQuery.data ?? [];
    return [...new Set([...modelOptions, ...fetched])].sort((a, b) => a.localeCompare(b));
  }, [modelCatalogQuery.data, modelOptions]);

  const loadState = () => {
    const session = services.orchestrator.ensureSession();
    return {
      sessionId: session.id,
      phase: session.current_phase,
      messages: services.messageService.list(session.id),
      artifacts: services.artifactService.list(session.id),
      currentArtifacts: services.artifactService.getCurrentArtifactSet(session.id),
      preview: services.orchestrator.buildPreviewModel(),
    } satisfies StudioPageState;
  };

  const { state } = useStudioState(loadState);

  function refreshStudioState() {
    refreshStudioStateQuery(queryClient, loadState);
  }

  const sendMutation = useStudioSendTurn({
    runUserTurn: services.orchestrator.runUserTurn.bind(services.orchestrator),
    setStatusWord,
    appendTrace,
    appendLlmExchange,
    traceUi,
    setLastRunResult,
    setLatestError,
    refreshStudioState,
  });

  const generateMutation = useStudioGenerateInitial({
    generateInitial: services.orchestrator.generateInitial.bind(services.orchestrator),
    setStatusWord,
    appendTrace,
    appendLlmExchange,
    traceUi,
    setLastRunResult,
    setLatestError,
    refreshStudioState,
  });
  const isBusy = sendMutation.isPending || generateMutation.isPending;
  const currentPlanRecord = useMemo(() => {
    return (
      state.artifacts
        .filter((artifact) => artifact.artifact_type === 'plan' && artifact.is_current)
        .sort((a, b) => b.version - a.version)[0] ?? null
    );
  }, [state.artifacts]);

  useEffect(() => {
    services.openAiClient.setModel(selectedModel);
  }, [selectedModel, services.openAiClient]);

  useEffect(() => {
    const shouldAutoGenerate =
      state.phase === 'phase2_plan' &&
      state.currentArtifacts.plan?.generation_ready === true &&
      !!currentPlanRecord &&
      !isBusy &&
      autoGeneratedPlanVersionRef.current !== currentPlanRecord.version;

    if (!shouldAutoGenerate) {
      return;
    }

    autoGeneratedPlanVersionRef.current = currentPlanRecord.version;
    setLatestError(null);
    traceUi('generate.auto', 'Auto-generation triggered from ready plan.', 'info', {
      planVersion: currentPlanRecord.version,
    });
    void generateMutation.mutateAsync();
  }, [
    currentPlanRecord,
    generateMutation,
    isBusy,
    state.currentArtifacts.plan?.generation_ready,
    state.phase,
    traceUi,
  ]);

  async function handleSend(text: string) {
    setLatestError(null);
    await sendMutation.mutateAsync(text);
  }

  async function handleGenerate() {
    setLatestError(null);
    await generateMutation.mutateAsync();
  }

  function handleExport() {
    const snapshot = services.store.snapshot();
    const bundle = buildStudioBundle({
      session: snapshot.studio_session,
      messages: snapshot.studio_messages,
      artifacts: snapshot.studio_artifacts,
    });
    downloadStudioBundle(bundle);
  }

  function handleDownloadDebug() {
    const snapshot = services.store.snapshot();
    const debugBundle = buildStudioDebugBundle({
      session: snapshot.studio_session,
      messages: snapshot.studio_messages,
      artifacts: snapshot.studio_artifacts,
      currentArtifacts: state.currentArtifacts,
      preview: state.preview,
      debugMode,
      statusWord,
      latestError,
      lastRunResult,
      selectedModel,
      debugTraces,
      llmExchanges,
    });
    downloadStudioDebugBundle(debugBundle);
    traceUi('debug.download', 'Downloaded studio debug bundle.');
  }

  function handleReset() {
    const confirmed = window.confirm(
      isBusy
        ? 'Generation is in progress. Force reset and restart Studio now?'
        : 'Reset Studio and clear session, messages, and artifacts?',
    );
    if (!confirmed) {
      traceUi('studio.reset.cancelled', 'Reset cancelled by user.');
      return;
    }

    traceUi('studio.reset.confirmed', 'Resetting studio session state.', 'warn', { busy: isBusy });
    services.store.commit({
      studio_session: null,
      studio_messages: [],
      studio_artifacts: [],
    });

    autoGeneratedPlanVersionRef.current = null;
    setStatusWord(null);
    setLatestError(null);
    setLastRunResult(null);
    setDebugMode(true);
    setDebugTraces([]);
    setLlmExchanges([]);

    if (isBusy) {
      window.location.reload();
      return;
    }

    refreshStudioState();
  }

  return (
    <div className="flex h-full flex-col bg-background text-foreground">
      <div className="flex items-center gap-2 border-b border-border px-4 py-2">
        <Button type="button" variant="ghost" size="sm" onClick={() => navigate(backPath)}>
          <ArrowLeft className="h-4 w-4" />
          Launchpad
        </Button>
        <span className="text-sm font-semibold">IKARY Studio</span>
        <div className="ml-4 flex items-center gap-2">
          <span className="text-xs text-muted-foreground">Model</span>
          <select
            value={selectedModel}
            onChange={(event) => setSelectedModel(event.target.value)}
            disabled={isBusy}
            className="h-8 rounded-md border border-input bg-background px-2 text-xs text-foreground outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-60"
          >
            {allModelOptions.map((model) => (
              <option key={model} value={model}>
                {model}
              </option>
            ))}
          </select>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => void modelCatalogQuery.refetch()}
            disabled={isBusy || !services.openAiClient.isConfigured()}
          >
            <RefreshCw className="h-4 w-4" />
            Sync
          </Button>
        </div>
        <div className="ml-auto flex items-center gap-2">
          <Button type="button" variant="secondary" size="sm" onClick={handleReset}>
            <RotateCcw className="h-4 w-4" />
            Reset
          </Button>
          <Button type="button" variant="outline" size="sm" onClick={handleDownloadDebug}>
            <Bug className="h-4 w-4" />
            Download Debug
          </Button>
          <Button type="button" variant="outline" size="sm" onClick={handleExport}>
            <Download className="h-4 w-4" />
            Export Bundle
          </Button>
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
        <StudioChatPane
          phase={state.phase}
          messages={state.messages}
          discovery={state.currentArtifacts.discovery}
          plan={state.currentArtifacts.plan}
          isBusy={isBusy}
          statusWord={statusWord}
          latestError={latestError}
          onSend={handleSend}
          onGenerateInitial={handleGenerate}
        />

        <StudioPreviewPane
          preview={state.preview}
          currentArtifacts={state.currentArtifacts}
          isBusy={isBusy}
          statusWord={statusWord}
          latestError={latestError}
          debugMode={debugMode}
          onDebugModeChange={setDebugMode}
          lastRunResult={lastRunResult}
          debugTraces={debugTraces}
        />
      </div>
    </div>
  );
}
