/**
 * AUTO-GENERATED FILE.
 *
 * Generated by libs/cell-contract-core/scripts/generate-schema-module-graph.mjs
 * Do not edit manually.
 */

export type SchemaModuleCategory =
  | 'entity'
  | 'manifest'
  | 'policy'
  | 'presentation'
  | 'validation'
  | 'validation_issue'
  | 'internal';

export interface SchemaModuleNode {
  readonly id: string;
  readonly sourcePath: string;
  readonly category: SchemaModuleCategory;
  readonly publicSchemaName?: string;
}

export interface SchemaModuleEdge {
  readonly from: string;
  readonly to: string;
  readonly kind: 'import';
}

export interface SchemaModuleUnresolvedImport {
  readonly from: string;
  readonly specifier: string;
  readonly resolvedPath: string;
}

export interface SchemaModuleGraph {
  readonly nodes: readonly SchemaModuleNode[];
  readonly importEdges: readonly SchemaModuleEdge[];
  readonly unresolvedImports: readonly SchemaModuleUnresolvedImport[];
}

export const CELL_SCHEMA_MODULE_GRAPH: SchemaModuleGraph = {
  nodes: [
    {
      id: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
      sourcePath: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
      category: 'validation',
      publicSchemaName: 'CrossEntityValidatorRefSchema',
    },
    {
      id: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'DisplayDefinitionSchema',
    },
    {
      id: 'src/contract/entity/EntityDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/EntityDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'EntityDefinitionSchema',
    },
    {
      id: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
      category: 'validation',
      publicSchemaName: 'EntityRuleDefinitionSchema',
    },
    {
      id: 'src/contract/entity/EntityValidationSchema.ts',
      sourcePath: 'src/contract/entity/EntityValidationSchema.ts',
      category: 'entity',
      publicSchemaName: 'EntityValidationSchema',
    },
    {
      id: 'src/contract/entity/event/EventDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/event/EventDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'EventDefinitionSchema',
    },
    {
      id: 'src/contract/entity/field/ComputedFieldDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/field/ComputedFieldDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'ComputedFieldDefinitionSchema',
    },
    {
      id: 'src/contract/entity/field/FieldDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/field/FieldDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'FieldDefinitionSchema',
    },
    {
      id: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
      category: 'validation',
      publicSchemaName: 'FieldRuleDefinitionSchema',
    },
    {
      id: 'src/contract/entity/field/FieldRuleTypeSchema.ts',
      sourcePath: 'src/contract/entity/field/FieldRuleTypeSchema.ts',
      category: 'validation',
      publicSchemaName: 'FieldRuleTypeSchema',
    },
    {
      id: 'src/contract/entity/field/FieldValidationSchema.ts',
      sourcePath: 'src/contract/entity/field/FieldValidationSchema.ts',
      category: 'entity',
    },
    {
      id: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'LifecycleDefinitionSchema',
    },
    {
      id: 'src/contract/entity/policy/ActionPolicySchema.ts',
      sourcePath: 'src/contract/entity/policy/ActionPolicySchema.ts',
      category: 'policy',
      publicSchemaName: 'ActionPolicySchema',
    },
    {
      id: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
      category: 'policy',
      publicSchemaName: 'EntityPoliciesDefinitionSchema',
    },
    {
      id: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
      category: 'policy',
      publicSchemaName: 'FieldPoliciesDefinitionSchema',
    },
    {
      id: 'src/contract/entity/policy/PolicyScopeSchema.ts',
      sourcePath: 'src/contract/entity/policy/PolicyScopeSchema.ts',
      category: 'policy',
      publicSchemaName: 'PolicyScopeSchema',
    },
    {
      id: 'src/contract/entity/relation/RelationDefinitionSchema.ts',
      sourcePath: 'src/contract/entity/relation/RelationDefinitionSchema.ts',
      category: 'entity',
      publicSchemaName: 'RelationDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
      category: 'manifest',
      publicSchemaName: 'CapabilityDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
      category: 'manifest',
      publicSchemaName: 'CapabilityInputDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/capability/CapabilityInputTypeSchema.ts',
      sourcePath: 'src/contract/manifest/capability/CapabilityInputTypeSchema.ts',
      category: 'manifest',
      publicSchemaName: 'CapabilityInputTypeSchema',
    },
    {
      id: 'src/contract/manifest/CellManifestV1Schema.ts',
      sourcePath: 'src/contract/manifest/CellManifestV1Schema.ts',
      category: 'manifest',
      publicSchemaName: 'CellManifestV1Schema',
    },
    {
      id: 'src/contract/manifest/CellMetadataSchema.ts',
      sourcePath: 'src/contract/manifest/CellMetadataSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/CellSpecSchema.ts',
      sourcePath: 'src/contract/manifest/CellSpecSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
      sourcePath: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
      category: 'manifest',
      publicSchemaName: 'DomainEventActorSchema',
    },
    {
      id: 'src/contract/manifest/domain-event/DomainEventActorTypeSchema.ts',
      sourcePath: 'src/contract/manifest/domain-event/DomainEventActorTypeSchema.ts',
      category: 'manifest',
      publicSchemaName: 'DomainEventActorTypeSchema',
    },
    {
      id: 'src/contract/manifest/domain-event/DomainEventEntityRefSchema.ts',
      sourcePath: 'src/contract/manifest/domain-event/DomainEventEntityRefSchema.ts',
      category: 'manifest',
      publicSchemaName: 'DomainEventEntityRefSchema',
    },
    {
      id: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
      sourcePath: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
      category: 'manifest',
      publicSchemaName: 'DomainEventEnvelopeSchema',
    },
    {
      id: 'src/contract/manifest/lifecycle/LifecycleTransitionDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/lifecycle/LifecycleTransitionDefinitionSchema.ts',
      category: 'manifest',
      publicSchemaName: 'LifecycleTransitionDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/navigation/NavigationDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/navigation/NavigationDefinitionSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/navigation/NavigationItemSchema.ts',
      sourcePath: 'src/contract/manifest/navigation/NavigationItemSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/page/PageDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/page/PageDefinitionSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/page/PageTypeSchema.ts',
      sourcePath: 'src/contract/manifest/page/PageTypeSchema.ts',
      category: 'manifest',
    },
    {
      id: 'src/contract/manifest/role/RoleDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/role/RoleDefinitionSchema.ts',
      category: 'policy',
      publicSchemaName: 'RoleDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/shell/AppShellDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/shell/AppShellDefinitionSchema.ts',
      category: 'manifest',
      publicSchemaName: 'AppShellDefinitionSchema',
    },
    {
      id: 'src/contract/manifest/shell/CellMountDefinitionSchema.ts',
      sourcePath: 'src/contract/manifest/shell/CellMountDefinitionSchema.ts',
      category: 'manifest',
      publicSchemaName: 'CellMountDefinitionSchema',
    },
    {
      id: 'src/semantic/ValidationErrorResponseSchema.ts',
      sourcePath: 'src/semantic/ValidationErrorResponseSchema.ts',
      category: 'validation_issue',
      publicSchemaName: 'ValidationErrorResponseSchema',
    },
    {
      id: 'src/semantic/ValidationIssueSchema.ts',
      sourcePath: 'src/semantic/ValidationIssueSchema.ts',
      category: 'validation_issue',
      publicSchemaName: 'ValidationIssueSchema',
    },
    {
      id: 'src/semantic/ValidationScopeSchema.ts',
      sourcePath: 'src/semantic/ValidationScopeSchema.ts',
      category: 'validation_issue',
      publicSchemaName: 'ValidationScopeSchema',
    },
    {
      id: 'src/shared/ValidationSeveritySchema.ts',
      sourcePath: 'src/shared/ValidationSeveritySchema.ts',
      category: 'validation_issue',
      publicSchemaName: 'ValidationSeveritySchema',
    },
  ],
  importEdges: [
    {
      from: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
      to: 'src/shared/ValidationSeveritySchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/EntityValidationSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/event/EventDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/field/ComputedFieldDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/field/FieldDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/entity/relation/RelationDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityDefinitionSchema.ts',
      to: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
      to: 'src/shared/ValidationSeveritySchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityValidationSchema.ts',
      to: 'src/contract/entity/CrossEntityValidatorRefSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/EntityValidationSchema.ts',
      to: 'src/contract/entity/EntityRuleDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/field/FieldDefinitionSchema.ts',
      to: 'src/contract/entity/display/DisplayDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/field/FieldDefinitionSchema.ts',
      to: 'src/contract/entity/field/FieldValidationSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
      to: 'src/contract/entity/field/FieldRuleTypeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
      to: 'src/shared/ValidationSeveritySchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/field/FieldValidationSchema.ts',
      to: 'src/contract/entity/field/FieldRuleDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/lifecycle/LifecycleDefinitionSchema.ts',
      to: 'src/contract/manifest/lifecycle/LifecycleTransitionDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/policy/ActionPolicySchema.ts',
      to: 'src/contract/entity/policy/PolicyScopeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/policy/EntityPoliciesDefinitionSchema.ts',
      to: 'src/contract/entity/policy/ActionPolicySchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/entity/policy/FieldPoliciesDefinitionSchema.ts',
      to: 'src/contract/entity/policy/ActionPolicySchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/capability/CapabilityDefinitionSchema.ts',
      to: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/capability/CapabilityInputDefinitionSchema.ts',
      to: 'src/contract/manifest/capability/CapabilityInputTypeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellManifestV1Schema.ts',
      to: 'src/contract/manifest/CellMetadataSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellManifestV1Schema.ts',
      to: 'src/contract/manifest/CellSpecSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/entity/EntityDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/manifest/navigation/NavigationDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/manifest/page/PageDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/manifest/role/RoleDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/manifest/shell/AppShellDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/CellSpecSchema.ts',
      to: 'src/contract/manifest/shell/CellMountDefinitionSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
      to: 'src/contract/manifest/domain-event/DomainEventActorTypeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
      to: 'src/contract/manifest/domain-event/DomainEventActorSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/domain-event/DomainEventEnvelopeSchema.ts',
      to: 'src/contract/manifest/domain-event/DomainEventEntityRefSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/navigation/NavigationDefinitionSchema.ts',
      to: 'src/contract/manifest/navigation/NavigationItemSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/contract/manifest/page/PageDefinitionSchema.ts',
      to: 'src/contract/manifest/page/PageTypeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/semantic/ValidationErrorResponseSchema.ts',
      to: 'src/semantic/ValidationIssueSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/semantic/ValidationIssueSchema.ts',
      to: 'src/semantic/ValidationScopeSchema.ts',
      kind: 'import',
    },
    {
      from: 'src/semantic/ValidationIssueSchema.ts',
      to: 'src/shared/ValidationSeveritySchema.ts',
      kind: 'import',
    },
  ],
  unresolvedImports: [],
} as const;
