export const AI_ERROR_CODES = {
  PROMPT_INJECTION_DETECTED: 'AI_PROMPT_INJECTION_DETECTED',
  INPUT_TOO_LARGE: 'AI_INPUT_TOO_LARGE',
  BUDGET_EXHAUSTED: 'AI_BUDGET_EXHAUSTED',
  PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  FEATURE_DISABLED: 'AI_FEATURE_DISABLED',
  NO_PROVIDER_AVAILABLE: 'AI_NO_PROVIDER_AVAILABLE',
} as const;

export type AiErrorCode = (typeof AI_ERROR_CODES)[keyof typeof AI_ERROR_CODES];
